// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfileServer.Database;

#nullable disable

namespace ProfileServer.Database.Migrations
{
    [DbContext(typeof(PerformanceDbContext))]
    [Migration("20250515094447_Delta reports")]
    partial class Deltareports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ProfileServer.Database.PerformanceReport", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("averageFrametime")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("created")
                        .HasColumnType("TEXT");

                    b.Property<string>("csvName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("maxFrameTime")
                        .HasColumnType("REAL");

                    b.Property<ulong>("messageId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("percentile95")
                        .HasColumnType("REAL");

                    b.Property<float>("percentile99")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("PerformanceReports");
                });
#pragma warning restore 612, 618
        }
    }
}
